<?php
/*
Plugin Name: Yamli
Plugin URI: http://www.fouad.fm/yamli-wordpress-plug-in/
Description: Using Yamli wih posts editor
Author: Fouad Masoud
Version: 1.5 and later
Author URI: http://www.fouad.fm
*/

// This just echoes the html generated by the Yamli API http://www.yamli.com/api/setup/ar/
// With some javascript enhansments to make all textareas have the yamli functionality 
function Yamli() {
	global $chosen;
	echo "
		<!-- YAMLI CODE START -->
		<script type='text/javascript' src='http://api.yamli.com/js/yamli_api.js'></script>
		<script type='text/javascript'>
			var text_area = document.getElementsByTagName('textarea');
			if (typeof(Yamli) == 'object' && Yamli.init( { uiLanguage: 'en' , startMode: 'offOrUserDefault' } )){
			    for(i=0; i < text_area.length; i++){
                                if (!text_area[i].getAttribute('id')){
                                    var quick_id = 'yamli_textarea_'+i;
                                    text_area[i].setAttribute('id', quick_id)
                                }
			    	Yamli.yamlify( text_area[i].getAttribute('id').toString(), { settingsPlacement: 'inside' } );
			    }
			  }
			  Yamli.yamlify( 'title', { settingsPlacement: 'inside' } );
		</script>
		<!-- YAMLI CODE END -->";
}

// Now we set that function up to execute when the admin_footer and wp_footer actions are called
add_action('admin_footer', 'Yamli');
add_action('wp_footer', 'Yamli');

?>